/*
 * event.h - event handling helpers
 *
 * Adapted from AwesomeWM's event.c for somewm (Wayland compositor)
 * Copyright © 2007-2009 Julien Danjou <julien@danjou.info>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */

#ifndef SOMEWM_EVENT_H
#define SOMEWM_EVENT_H

#include <lua.h>
#include <stdbool.h>
#include <stdint.h>
#include "globalconf.h"

/* Wayland button event structure (replaces xcb_button_press_event_t) */
typedef struct {
    uint32_t button;       /* Button code (Linux input code) */
    uint32_t state;        /* Modifier state */
    int x, y;              /* Event coordinates (window-relative) */
    bool is_press;         /* true = press, false = release */
} button_event_t;

/* Generic button event callback - iterates button array and emits signals
 * Generated by DO_EVENT_HOOK_CALLBACK macro */
void event_button_callback(button_event_t *ev, button_array_t *arr,
                           lua_State *L, int oud, int nargs, void *data);

/** Record that the given drawable contains the pointer.
 * Emits mouse::enter/leave signals on drawables for widget hover events.
 */
void event_drawable_under_mouse(lua_State *L, int ud);

#endif /* SOMEWM_EVENT_H */
