/*
 * event.h - event handling helpers
 *
 * Adapted from AwesomeWM's event.c for somewm (Wayland compositor)
 * Copyright © 2007-2009 Julien Danjou <julien@danjou.info>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */

#ifndef SOMEWM_EVENT_H
#define SOMEWM_EVENT_H

#include <lua.h>
#include <stdbool.h>
#include <stdint.h>
#include "globalconf.h"

/* Wayland button event structure (replaces xcb_button_press_event_t) */
typedef struct {
    uint32_t button;       /* Button code (Linux input code) */
    uint32_t state;        /* Modifier state */
    int x, y;              /* Event coordinates (window-relative) */
    bool is_press;         /* true = press, false = release */
} button_event_t;

/* Button matching function - checks if button binding matches event */
bool event_button_match(button_event_t *ev, button_t *b, void *data);

/* Generic button event callback - iterates button array and emits signals
 * Generated by DO_EVENT_HOOK_CALLBACK macro */
void event_button_callback(button_event_t *ev, button_array_t *arr,
                           lua_State *L, int oud, int nargs, void *data);

/* Emit button::press or button::release signal on object at stack top
 * Pushes x, y, button, modifiers as arguments */
void event_emit_button(lua_State *L, button_event_t *ev);

/* Handle mousegrabber if active - returns true if event consumed */
bool event_handle_mousegrabber(double x, double y, int button_states[5]);

#endif /* SOMEWM_EVENT_H */
