/*
 * systray.h - StatusNotifierItem (SNI) systray support
 *
 * Implements a first-class widget approach where each tray icon
 * is a proper Lua object that can be styled individually.
 *
 * This is a Wayland-native implementation using D-Bus SNI protocol,
 * NOT the X11 XEmbed-based systray from AwesomeWM.
 *
 * Copyright © 2024 somewm contributors
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */

#ifndef SOMEWM_OBJECTS_SYSTRAY_H
#define SOMEWM_OBJECTS_SYSTRAY_H

#include <lua.h>
#include <stdbool.h>
#include <cairo/cairo.h>
#include "common/luaclass.h"
#include "common/luaobject.h"
#include "common/array.h"

/**
 * StatusNotifierItem - represents a single tray icon
 *
 * Each systray_item_t is a Lua object that can be wrapped in a widget
 * for full styling control (opacity, shape, border, background, etc.)
 *
 * Properties are fetched from D-Bus and cached here. When the D-Bus
 * item emits signals (NewIcon, NewStatus, etc.), we update the cache
 * and emit corresponding Lua signals.
 */
typedef struct systray_item_t {
    LUA_OBJECT_HEADER

    /* D-Bus identification */
    char *bus_name;         /**< D-Bus service name (e.g., ":1.234") */
    char *object_path;      /**< D-Bus object path (e.g., "/StatusNotifierItem") */

    /* Unique identifier for tracking */
    char *id;               /**< Application ID from StatusNotifierItem */

    /* Basic properties from StatusNotifierItem interface */
    char *title;            /**< Display title */
    char *app_name;         /**< Process name (derived from PID) */
    char *status;           /**< "Active", "Passive", or "NeedsAttention" */
    char *category;         /**< "ApplicationStatus", "Communications", etc. */

    /* Icon data - prefer icon_name, fallback to pixmap */
    char *icon_name;        /**< Freedesktop icon name (preferred) */
    cairo_surface_t *icon;  /**< Rendered icon surface */
    int icon_width;         /**< Icon width in pixels */
    int icon_height;        /**< Icon height in pixels */

    /* Attention icon (when status == "NeedsAttention") */
    char *attention_icon_name;
    cairo_surface_t *attention_icon;

    /* Overlay icon (small badge displayed on top of main icon) */
    char *overlay_icon_name;
    cairo_surface_t *overlay_icon;

    /* Tooltip data */
    char *tooltip_title;    /**< Tooltip title */
    char *tooltip_body;     /**< Tooltip description/body */
    char *tooltip_icon_name;/**< Tooltip icon name */

    /* Menu (DBusMenu interface) */
    char *menu_path;        /**< D-Bus object path for menu interface */

    /* Icon theme path (custom theme search path) */
    char *icon_theme_path;

    /* Behavior flags */
    bool item_is_menu;      /**< true if clicking should show menu, not activate */

    /* Internal state */
    bool is_valid;          /**< false if D-Bus item disappeared */
} systray_item_t;

/* Array type for tracking all items */
ARRAY_TYPE(systray_item_t *, systray_item)

/* Systray item class for Lua object system */
extern lua_class_t systray_item_class;

/* Class setup - call during luaA_init() */
void systray_item_class_setup(lua_State *L);

/* Item lifecycle - systray_item_new() is generated by LUA_OBJECT_FUNCS macro */
systray_item_t *systray_item_create(lua_State *L);  /* Creates and initializes a new item */
void systray_item_destroy(systray_item_t *item);

/* Icon management */
void systray_item_set_icon_from_pixmap(systray_item_t *item,
                                       const unsigned char *data,
                                       int width, int height);
void systray_item_set_icon_from_name(systray_item_t *item,
                                     const char *icon_name,
                                     int size);

/* Overlay icon management */
void systray_item_set_overlay_from_pixmap(systray_item_t *item,
                                          const unsigned char *data,
                                          int width, int height);
void systray_item_clear_overlay(systray_item_t *item);

/* Signal emission helpers (call from D-Bus callbacks) */
void systray_item_emit_property_changed(systray_item_t *item,
                                        const char *property);

/* Global signals */
void systray_emit_item_added(systray_item_t *item);
void systray_emit_item_removed(systray_item_t *item);

/* Get all current items (for iteration) */
systray_item_array_t *systray_get_items(void);

#endif /* SOMEWM_OBJECTS_SYSTRAY_H */
/* vim: filetype=c:expandtab:shiftwidth=4:tabstop=8:softtabstop=4:textwidth=80 */
